# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugo-green-tea"
license = "MIT"
licenselink = "https://github.com/nakaokat/hugo-green-tea/LICENSE.md"
description = "Simple and Clean Hugo template based green color."
homepage = "http://nakaokat.github.io"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Taiki Nakaoka"
  homepage = "http://nakaokat.github.io"

